version: "3"

services:
  api:
    image: api:latest
    build:
      context: .
      dockerfile: ./Stock.API/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"